[package]
name = "karl"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
structopt = "0.3"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
directories = "4.0"
